'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SORTLIST = exports.SORTLIST = 'SORTLIST';
var CHANGE_SELECTION = exports.CHANGE_SELECTION = 'CHANGE_SELECTION';
var CHANGE_FILTER = exports.CHANGE_FILTER = 'CHANGE_FILTER';
var TORRENT_LIST = exports.TORRENT_LIST = 'TORRENT_LIST';
var SET_BUTTON_STATE = exports.SET_BUTTON_STATE = 'BUTTON_STATE';
var SELECTION_HASHES = exports.SELECTION_HASHES = 'SELECTION_HASHES';
var SELECTED_TAB = exports.SELECTED_TAB = 'SELECTED_TAB';
var PEER_LIST = exports.PEER_LIST = 'PEER_LIST';
var FILE_LIST = exports.FILE_LIST = 'FILE_LIST';
var CHANGE_FILE_SELECTION = exports.CHANGE_FILE_SELECTION = 'CHANGE_FILE_SELECTION';
var NEW_RSS_FEED_STORE = exports.NEW_RSS_FEED_STORE = 'NEW_RSS_FEED_STORE';
var RSS_MODAL_OPEN_STATE = exports.RSS_MODAL_OPEN_STATE = 'RSS_MODAL_OPEN_STATE';
var RSS_TORRENT_LIST = exports.RSS_TORRENT_LIST = 'RSS_TORRENT_LIST';